import React, { useEffect, useState } from "react";
import {
  ShieldCheck, Lock, KeyRound, Users, Trash2, History, Camera,
  Plus, RefreshCw, ArrowLeft, LogOut, Palette, Save, Eye,
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import DashboardLayout from "./DashboardLayout";
import { useSettings } from "../../lib/settings";
import { useToast } from "../../hooks/use-toast";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const roles = ["admin", "supervisor", "crew"];

const roleColor = (r) => {
  if (r === "admin") return "bg-rose-100 text-rose-700 border-rose-200";
  if (r === "supervisor") return "bg-indigo-100 text-indigo-700 border-indigo-200";
  return "bg-slate-100 text-slate-700 border-slate-200";
};

const TwoFAGate = ({ onSuccess }) => {
  const [code, setCode] = useState("");
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState("");
  const { toast } = useToast();
  const navigate = useNavigate();

  const submit = async (e) => {
    e.preventDefault();
    setError("");
    setVerifying(true);
    try {
      const res = await axios.post(`${API}/admin/verify`, { code });
      if (res.data.verified) {
        onSuccess(res.data.token);
        toast({ title: "Access granted", description: "Welcome, admin." });
      } else {
        setError(res.data.message || "Invalid code");
      }
    } catch (err) {
      setError(err.response?.data?.detail || err.message);
    } finally {
      setVerifying(false);
    }
  };

  return (
    <DashboardLayout title="Admin Access" subtitle="Two-factor authentication required">
      <div className="max-w-md mx-auto">
        <button
          onClick={() => navigate("/dashboard/settings")}
          className="inline-flex items-center gap-1.5 text-[12px] text-slate-500 hover:text-slate-800 mb-4"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to settings
        </button>
        <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
          <div className="flex justify-center mb-4">
            <div className="w-14 h-14 rounded-full bg-brand-100 flex items-center justify-center">
              <ShieldCheck className="w-7 h-7 text-brand-700" />
            </div>
          </div>
          <h2 className="text-center text-[18px] font-semibold text-slate-900 mb-1">Enter 6-digit code</h2>
          <p className="text-center text-[12px] text-slate-500 mb-6">
            The code was generated by your authenticator. For this demo use <span className="font-mono font-semibold text-slate-700">123456</span>.
          </p>
          <form onSubmit={submit}>
            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/[^0-9]/g, ""))}
              placeholder="••••••"
              autoFocus
              className="w-full h-12 px-3 text-center text-[22px] tracking-[0.5em] font-mono border border-slate-200 rounded-lg outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-200"
            />
            {error && (
              <div className="mt-3 p-2 rounded-md bg-rose-50 border border-rose-200 text-[12px] text-rose-700 text-center">
                {error}
              </div>
            )}
            <button
              type="submit"
              disabled={code.length !== 6 || verifying}
              className="w-full h-11 mt-4 rounded-lg bg-brand-700 hover:bg-brand-800 text-white text-[13px] font-medium transition-colors inline-flex items-center justify-center gap-2 disabled:opacity-50"
            >
              <KeyRound className="w-4 h-4" />
              {verifying ? "Verifying…" : "Unlock admin"}
            </button>
          </form>
        </div>
      </div>
    </DashboardLayout>
  );
};

const UsersTab = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", role: "crew" });
  const { toast } = useToast();

  const load = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/admin/users`);
      setUsers(res.data);
    } catch (err) {
      toast({ title: "Load failed", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const create = async (e) => {
    e.preventDefault();
    if (!form.name || !form.email) return;
    try {
      const res = await axios.post(`${API}/admin/users`, form);
      setUsers((u) => [res.data, ...u]);
      setForm({ name: "", email: "", role: "crew" });
      toast({ title: "User added", description: `${res.data.email} · ${res.data.role}` });
    } catch (err) {
      toast({ title: "Add failed", description: err.message, variant: "destructive" });
    }
  };

  const remove = async (id) => {
    if (!window.confirm("Delete this user? A copy is kept in the audit trail.")) return;
    try {
      await axios.delete(`${API}/admin/users/${id}`);
      setUsers((u) => u.filter((x) => x.id !== id));
      toast({ title: "User deleted" });
    } catch (err) {
      toast({ title: "Delete failed", description: err.message, variant: "destructive" });
    }
  };

  return (
    <div className="space-y-4">
      <form onSubmit={create} className="bg-white rounded-xl border border-slate-200 p-4 grid grid-cols-1 md:grid-cols-4 gap-2">
        <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}
          placeholder="Full name" className="h-10 px-3 border border-slate-200 rounded-lg text-[13px] outline-none focus:border-slate-400" />
        <input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}
          placeholder="email@company.com" className="h-10 px-3 border border-slate-200 rounded-lg text-[13px] outline-none focus:border-slate-400" />
        <select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}
          className="h-10 px-3 border border-slate-200 rounded-lg text-[13px] bg-white outline-none focus:border-slate-400">
          {roles.map((r) => <option key={r} value={r}>{r}</option>)}
        </select>
        <button className="h-10 rounded-lg bg-slate-900 hover:bg-slate-800 text-white text-[13px] font-medium inline-flex items-center justify-center gap-1.5">
          <Plus className="w-3.5 h-3.5" /> Add user
        </button>
      </form>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <div className="px-5 py-3.5 border-b border-slate-200 flex items-center justify-between">
          <h3 className="text-[14px] font-semibold text-slate-900">Team members ({users.length})</h3>
          <button onClick={load} className="w-8 h-8 rounded-lg hover:bg-slate-100 text-slate-500 flex items-center justify-center">
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          </button>
        </div>
        {users.length === 0 && !loading && (
          <div className="p-10 text-center text-[13px] text-slate-500">No users yet. Add your first team member above.</div>
        )}
        {users.map((u) => (
          <div key={u.id} className="flex items-center gap-3 px-5 py-3 border-b border-slate-100 last:border-0">
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-brand-400 to-brand-700 text-white text-[11px] font-semibold flex items-center justify-center">
              {u.name.split(" ").map((n) => n[0]).slice(0, 2).join("")}
            </div>
            <div className="flex-1 min-w-0">
              <div className="text-[13px] font-medium text-slate-900 truncate">{u.name}</div>
              <div className="text-[11px] text-slate-500 truncate">{u.email}</div>
            </div>
            <span className={`text-[10px] uppercase font-semibold px-2 py-0.5 rounded-full border ${roleColor(u.role)}`}>
              {u.role}
            </span>
            <button onClick={() => remove(u.id)} className="p-1.5 rounded hover:bg-rose-50 text-slate-400 hover:text-rose-600">
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

const AuditTab = () => {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const load = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/admin/audit`, { params: { limit: 200 } });
      setItems(res.data);
    } catch (err) {
      toast({ title: "Load failed", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const clearAll = async () => {
    if (!window.confirm("Permanently wipe the audit trail?")) return;
    await axios.delete(`${API}/admin/audit`);
    setItems([]);
    toast({ title: "Audit cleared" });
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
      <div className="px-5 py-3.5 border-b border-slate-200 flex items-center justify-between">
        <h3 className="text-[14px] font-semibold text-slate-900">Deleted records audit ({items.length})</h3>
        <div className="flex items-center gap-2">
          <button onClick={load} className="w-8 h-8 rounded-lg hover:bg-slate-100 text-slate-500 flex items-center justify-center">
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          </button>
          {items.length > 0 && (
            <button onClick={clearAll} className="h-8 px-3 rounded-lg text-[11px] font-medium text-slate-600 hover:text-rose-600 border border-slate-200 hover:border-rose-300 inline-flex items-center gap-1">
              <Trash2 className="w-3 h-3" /> Wipe
            </button>
          )}
        </div>
      </div>
      {items.length === 0 && (
        <div className="p-10 text-center text-[13px] text-slate-500">Nothing has been deleted yet.</div>
      )}
      {items.map((it) => (
        <div key={it.id} className="flex items-start gap-3 px-5 py-3 border-b border-slate-100 last:border-0">
          <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center flex-shrink-0">
            <History className="w-3.5 h-3.5 text-slate-500" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="text-[12px] font-semibold text-slate-900">
              {it.entity} · <span className="font-mono text-slate-500 font-normal">{it.original_id?.slice(0, 8)}</span>
            </div>
            <div className="text-[10px] text-slate-500">
              Deleted by {it.deleted_by} · {new Date(it.deleted_at).toLocaleString()}
            </div>
            <pre className="mt-1 text-[10px] text-slate-600 bg-slate-50 rounded p-2 max-h-24 overflow-y-auto font-mono">
{JSON.stringify(it.payload, null, 2).slice(0, 400)}
            </pre>
          </div>
        </div>
      ))}
    </div>
  );
};

const UnfiledTab = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const load = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/admin/watch/unsaved`);
      setAlerts(res.data);
    } catch (err) {
      toast({ title: "Load failed", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
      <div className="px-5 py-3.5 border-b border-slate-200 flex items-center justify-between">
        <h3 className="text-[14px] font-semibold text-slate-900">Unfiled camera footage ({alerts.length})</h3>
        <button onClick={load} className="w-8 h-8 rounded-lg hover:bg-slate-100 text-slate-500 flex items-center justify-center">
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
        </button>
      </div>
      {alerts.length === 0 && (
        <div className="p-10 text-center text-[13px] text-slate-500">All camera alerts have been filed. Nothing to review.</div>
      )}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 p-4">
        {alerts.map((a) => (
          <div key={a.id} className="rounded-lg border border-slate-200 overflow-hidden">
            {a.snapshot_b64 ? (
              <img
                src={a.snapshot_b64.startsWith("data:") ? a.snapshot_b64 : `data:image/jpeg;base64,${a.snapshot_b64}`}
                alt="frame"
                className="w-full aspect-video object-cover"
              />
            ) : (
              <div className="w-full aspect-video bg-slate-100 flex items-center justify-center">
                <Camera className="w-6 h-6 text-slate-400" />
              </div>
            )}
            <div className="p-3">
              <div className="text-[11px] font-semibold text-slate-500 uppercase">{a.severity}</div>
              <div className="text-[12px] text-slate-900 font-medium line-clamp-2">{a.alert}</div>
              <div className="text-[10px] text-slate-400 mt-1">{a.site} · {new Date(a.timestamp).toLocaleString()}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

const BrandingTab = () => {
  const { settings, update } = useSettings();
  const { toast } = useToast();
  return (
    <div className="bg-white rounded-xl border border-slate-200 p-5 max-w-lg">
      <div className="flex items-center gap-3 mb-5">
        <div className="w-11 h-11 rounded-full flex items-center justify-center text-white font-bold text-[14px]"
             style={{ backgroundColor: settings.brandColor }}>
          {settings.logoText}
        </div>
        <div>
          <div className="text-[14px] font-semibold text-slate-900">{settings.appName}</div>
          <div className="text-[11px] text-slate-500">Live preview</div>
        </div>
      </div>
      <div className="space-y-3">
        <div>
          <label className="text-[11px] font-semibold text-slate-600 uppercase mb-1 block">Brand color (hex)</label>
          <input type="color" value={settings.brandColor} onChange={(e) => update({ brandColor: e.target.value })}
            className="w-16 h-9 rounded-lg border border-slate-200 cursor-pointer" />
        </div>
        <div>
          <label className="text-[11px] font-semibold text-slate-600 uppercase mb-1 block">Logo text</label>
          <input type="text" maxLength={5} value={settings.logoText} onChange={(e) => update({ logoText: e.target.value })}
            className="w-24 h-9 px-2 border border-slate-200 rounded-lg text-[13px] text-center outline-none focus:border-slate-400" />
        </div>
        <div>
          <label className="text-[11px] font-semibold text-slate-600 uppercase mb-1 block">App name</label>
          <input type="text" value={settings.appName} onChange={(e) => update({ appName: e.target.value })}
            className="w-full h-9 px-3 border border-slate-200 rounded-lg text-[13px] outline-none focus:border-slate-400" />
        </div>
        <button
          onClick={() => toast({ title: "Branding saved", description: "Changes are already applied live." })}
          className="h-9 px-4 rounded-lg text-white text-[13px] font-medium inline-flex items-center gap-1.5"
          style={{ backgroundColor: settings.brandColor }}
        >
          <Save className="w-3.5 h-3.5" /> Save
        </button>
      </div>
    </div>
  );
};

const AdminPage = () => {
  const { adminToken, setAdminToken } = useSettings();
  const [tab, setTab] = useState("users");
  const navigate = useNavigate();

  if (!adminToken) return <TwoFAGate onSuccess={setAdminToken} />;

  const tabs = [
    { key: "users", label: "Users", icon: Users, node: <UsersTab /> },
    { key: "audit", label: "Deleted Audit", icon: History, node: <AuditTab /> },
    { key: "unfiled", label: "Unfiled Footage", icon: Camera, node: <UnfiledTab /> },
    { key: "branding", label: "Branding", icon: Palette, node: <BrandingTab /> },
  ];

  return (
    <DashboardLayout
      title="Admin Panel"
      subtitle="Users, audit trail, unfiled footage & branding"
      action={
        <button
          onClick={() => { setAdminToken(null); navigate("/dashboard/settings"); }}
          className="inline-flex items-center gap-1.5 h-9 px-3 rounded-lg bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-[13px] font-medium"
        >
          <LogOut className="w-3.5 h-3.5" /> Sign out admin
        </button>
      }
    >
      <div className="flex items-center gap-1 mb-4 border-b border-slate-200">
        {tabs.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`h-10 px-4 text-[13px] font-medium border-b-2 transition-colors inline-flex items-center gap-1.5 ${
              tab === t.key
                ? "border-brand-700 text-brand-700"
                : "border-transparent text-slate-600 hover:text-slate-900"
            }`}
          >
            <t.icon className="w-3.5 h-3.5" />
            {t.label}
          </button>
        ))}
      </div>
      {tabs.find((t) => t.key === tab)?.node}
    </DashboardLayout>
  );
};

export default AdminPage;
